clients/Makefile.am: do not LDADD libnutclient.la to libnutclientstub.la, we use them both in ultimate test program linking
This reverts commit c5b34c765edb4ae9d71079410a334f4cadd13d09
"tests/Makefile.am: do not LDADD libnutclient.la where we (also) use libnutclientstub.la":
(on Linux) without the "extra" link we get
	  CXXLD    cppunittest
	/usr/bin/ld: cppunittest-nutclienttest.o: undefined reference to symbol '_ZTIN3nut12NutExceptionE'
	/usr/bin/ld: /home/runner/work/nut/nut/clients/.libs/libnutclient.so.2: error adding symbols: DSO missing from command line
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>