drivers/eaton-pdu-marlin-helpers.c, drivers/snmp-ups-helpers.c: reword dummy upsdebugx() so it may be followed by semicolon
Avoid warning from `WITH_DMFMIB_SELFTEST` program builds:
	../../../drivers/snmp-ups-helpers.c:68:52: error: empty expression
		statement has no effect; remove unnecessary ';' to silence
		this warning [-Werror,-Wextra-semi-stmt]
	upsdebugx(3, "%s: US date = %s", __func__, usdate);

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>