docs/man/nhs_ser.txt, drivers/nhs_ser.c: introduce option flags for debug_pkt_raw, debug_pkt_data, debug_pkt_hwinfo [#2692]
Also helps avoid dead code and this warning:

        nhs_ser.c:467:13: error: unused function 'print_pkt_data' [-Werror,-Wunused-function]
        static void print_pkt_data(pkt_data data) {
                    ^

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>