clients/upsclient.c: define both fields of upscli_default_timeout explicitly after all [#2847]
Antique clang (3.4) refuses the standard-required single-token init of aggregate types:

	upsclient.c:162:50: error: missing field 'tv_usec' initializer [-Werror,-Wmissing-field-initializers]
	static struct timeval upscli_default_timeout = {0};
	                                                 ^
	1 error generated.
	make[4]: *** [upsclient.lo] Error 1

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>