drivers/nhs-nut.c: fix compiler complaints - unused methods [#2692]
Hide them away:

        nhs_ser.c:939:15: error: unused function 'strtolow' [-Werror,-Wunused-function]
        static char * strtolow(char* s) {
                      ^
        nhs_ser.c:902:12: error: unused function 'write_serial' [-Werror,-Wunused-function]
        static int write_serial(int fd, const char * dados, int size) {
                   ^
        2 errors generated.

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>