drivers/nutdrv_qx_voltronic-axpert.c: voltronic_sunny_fault(): use alarm[LARGEBUF] so that item->value[SMALLBUF] can fit with added markup [#1407]
...not that we expect problems with this, but compiler warns they are feasible:
    error: '%s' directive output may be truncated writing up to 511 bytes
           into a region of size 497 [-Werror=format-truncation=]

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>